FROM python

WORKDIR /app/
# Start Redis
RUN apt-get update && apt-get install -y redis-server

COPY start.sh /start.sh
RUN chmod +x /start.sh

COPY requirements.txt .

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

COPY . .

EXPOSE 6379

CMD ["/start.sh"]